# =====================================================================
# Makefile for axioms 
# =====================================================================


thmdoc:	
	rm -f *.doc
	create-axiom-doc ind
	create-axiom-doc bool
	@echo "===> axioms .doc files created"

